// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {app} from '../models';

export function GetAppStatus():Promise<app.AppStatus>;

export function GetAutoStableStatus():Promise<app.AutoStableStatus>;

export function GetConnectionStatus():Promise<app.ConnectionStatus>;

export function GetLogs(arg1:number):Promise<Array<app.LogLine>>;

export function GetProxyGroups():Promise<Array<app.ProxyGroupView>>;

export function LoadSubscription(arg1:string):Promise<void>;

export function LoadSubscriptionData(arg1:string,arg2:Array<number>):Promise<void>;

export function RecoverCoreIfNeeded():Promise<boolean>;

export function RestartCore():Promise<void>;

export function RunAutoStableTick():Promise<app.AutoStableActionResult>;

export function SelectAutoStableProxy(arg1:string):Promise<app.AutoStableActionResult>;

export function SelectProxy(arg1:string,arg2:string):Promise<void>;

export function SetAutoStableEnabled(arg1:boolean):Promise<void>;

export function SetSystemProxy(arg1:boolean):Promise<void>;

export function StartCore():Promise<void>;

export function StopCore():Promise<void>;
