// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAppStatus() {
  return window['go']['app']['App']['GetAppStatus']();
}

export function GetAutoStableStatus() {
  return window['go']['app']['App']['GetAutoStableStatus']();
}

export function GetConnectionStatus() {
  return window['go']['app']['App']['GetConnectionStatus']();
}

export function GetLogs(arg1) {
  return window['go']['app']['App']['GetLogs'](arg1);
}

export function GetProxyGroups() {
  return window['go']['app']['App']['GetProxyGroups']();
}

export function LoadSubscription(arg1) {
  return window['go']['app']['App']['LoadSubscription'](arg1);
}

export function LoadSubscriptionData(arg1, arg2) {
  return window['go']['app']['App']['LoadSubscriptionData'](arg1, arg2);
}

export function RecoverCoreIfNeeded() {
  return window['go']['app']['App']['RecoverCoreIfNeeded']();
}

export function RestartCore() {
  return window['go']['app']['App']['RestartCore']();
}

export function RunAutoStableTick() {
  return window['go']['app']['App']['RunAutoStableTick']();
}

export function SelectAutoStableProxy(arg1) {
  return window['go']['app']['App']['SelectAutoStableProxy'](arg1);
}

export function SelectProxy(arg1, arg2) {
  return window['go']['app']['App']['SelectProxy'](arg1, arg2);
}

export function SetAutoStableEnabled(arg1) {
  return window['go']['app']['App']['SetAutoStableEnabled'](arg1);
}

export function SetSystemProxy(arg1) {
  return window['go']['app']['App']['SetSystemProxy'](arg1);
}

export function StartCore() {
  return window['go']['app']['App']['StartCore']();
}

export function StopCore() {
  return window['go']['app']['App']['StopCore']();
}
